import pandas as pd
import numpy as np
import scipy as sc
import seaborn
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.ndimage.filters import gaussian_filter1d
#from scipy.ndimage import uniform_filter1d
from scipy.stats import beta
import sdeint
#!pip install kramersmoyal
from kramersmoyal import km
from sklearn.neighbors import KernelDensity
from scipy.stats import entropy


from .Data_cleaning import data_cleaning
from .Functions import data_filter, integrate_omega, KM_Coeff_1, KM_Coeff_2, daily_profile, power_mismatch, exp_decay, Euler_Maruyama, Increments, autocor 

grids = ['Balearic','Irish','Iceland']
models = ['model 1','model 2','model 3','model 4']

'''The bandwidth is chosen such that we receive a scmooth distribution'''


'''Model 1...'''
synth_data_model_1 = {}
'''adapt the parameter estimation to the particulat grids'''
for grid in grids:
  data = ...
  data = data_cleaning(data)
  if grid = 'Balearic':
    diff_drift = ...
  elif grid = 'Irish':
    bw_drift = ...
  elif grid = 'Iceland':
    bw_drift = ...
  c_1 = ...
  c_2 = ...
  Delta_P = ...
  epsilon = ...
  omega_synth_model_1 = Euler_Maruyama(...)
  synth_data_model_1(grid) = omega_synth_model_1

  '''Model 2...'''
synth_data_model_2 = {}
'''adapt the parameter estimation to the particulat grids'''
for grid in grids:
  data = ...
  data = data_cleaning(data)
  if grid = 'Balearic':
    diff_drift = ...
  elif grid = 'Irish':
    bw_drift = ...
  elif grid = 'Iceland':
    bw_drift = ...
  c_1 = ...
  c_2 = ...
  Delta_P = ...
  epsilon = ...
  omega_synth_model_2 = Euler_Maruyama(...)
  synth_data_model_2(grid) = omega_synth_model_2

   '''Model 3...'''
synth_data_model_3 = {}
'''adapt the parameter estimation to the particulat grids'''
for grid in grids:
  data = ...
  data = data_cleaning(data)
  if grid = 'Balearic':
    bw_drift = ...
  elif grid = 'Irish':
    bw_drift = ...
  elif grid = 'Iceland':
    bw_drift = ...
  c_1 = ...
  c_2 = ...
  Delta_P = ...
  epsilon = ...
  omega_synth_model_3 = Euler_Maruyama(...)
  synth_data_model_3(grid) = omega_synth_model_3
  
   '''Model 4...'''
synth_data_model_4 = {}
'''adapt the parameter estimation to the particulat grids'''
for grid in grids:
  data = ...
  data = data_cleaning(data)
  if grid = 'Balearic':
    diff_drift = ...
  elif grid = 'Irish':
    bw_drift = ...
  elif grid = 'Iceland':
    bw_drift = ...
  c_1 = ...
  c_2 = ...
  Delta_P = ...
  epsilon = ...
  omega_synth_model_4 = Euler_Maruyama(...)
  synth_data_model_4(grid) = omega_synth_model_4

